### ISSUE TITLE
Pi version

### ISSUE THREAD

**Issue by cdecc** [spidgorny/energy-monitor#2]
Hi, What version of a pi are you using?
I have a model 1 that I can use but I wonder if it would be powerfull enough.
I stll ahve to bu a camera, maybe the pi cam, or should I use a usb webcam for beter results?

Thx !

**Comment by spidgorny** [comment]
I have Pi Zero W which has WiFi built-in. You only need to process a frame in an hour. We are not talking about 60 FPS - just one frame every hour (or a minute).
I've used a WebCam which was easier to purchase and attach. Both would work. The new Pi camera has a night mode though - I had to use a small USB LED lamp to shine light on the meter at night.
